### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by sagnik** [jupyterlab/jupyterlab-google-drive#35]
I am getting this error from the command `jupyter labextension install @jupyterlab/google-drive`. npm version is **5.3.0**. Is there a directory where I should be during installation?

```
> npm pack @jupyterlab/google-drive
> node node-version-check.js
> npm pack /home/sagnik/jupyterlab_json_latest/labextension
> npm install
npm ERR! code ENOLOCAL
npm ERR! Could not install from "../extensions/component" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sagnik/.npm/_logs/2017-07-17T18_50_20_384Z-debug.log

Traceback (most recent call last):
  File "/home/sagnik/anaconda2/bin/jupyter-labextension", line 6, in <module>
    sys.exit(jupyterlab.labextensions.main())
  File "/home/sagnik/anaconda2/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/sagnik/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/sagnik/anaconda2/lib/python2.7/site-packages/jupyterlab/labextensions.py", line 167, in start
    super(LabExtensionApp, self).start()
  File "/home/sagnik/anaconda2/lib/python2.7/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/home/sagnik/anaconda2/lib/python2.7/site-packages/jupyterlab/labextensions.py", line 59, in start
    build(self.app_dir, logger=self.log)
  File "/home/sagnik/anaconda2/lib/python2.7/site-packages/jupyterlab/commands.py", line 478, in build
    run(['npm', 'install'], cwd=staging, logger=logger)
  File "/home/sagnik/anaconda2/lib/python2.7/site-packages/jupyterlab/commands.py", line 61, in run
    raise error
subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1
```

**Comment by ian-r-rose** [comment]
Hi @sagnik, it looks like the error is with `@jupyterlab/json-extension` (see the third line of your error log). Could you remove that labextension and try again?

**Comment by ian-r-rose** [comment]
Also, you should not need to be in a particular directory.

**Comment by sagnik** [comment]
right. I tried to install one extension with the same name, that failed, but is it carrying over to this extension?

**Comment by ian-r-rose** [comment]
Yes, every time you try to install an extension it tries to rebuild the bundle, so having a broken extension from some other source can interfere with installing `@jupyterlab/google-drive` (unfortunately). You probably need to disable that extension first (`jupyter labextension uninstall @jupyterlab/json-extension`, or something to that effect).

**Comment by sagnik** [comment]
ok, so i can confirm that once i do `rm ~/anaconda2/share/jupyter/lab/extensions/jupyterlab_json_labextension-0.20.2.tgz` , i.e., remove the previous unsuccessful extension from the anaconda shared dir, the installation works. don't know if that should be considered a bug or not.

**Comment by ian-r-rose** [comment]
It is expected behavior, though certainly we should smooth that out in the future. In any event, it is more of an issue with the main jupyterlab/jupyterlab repository.
