### ISSUE TITLE
installation error: Can't resolve 'jquery'

### ISSUE THREAD

**Issue by danpf** [jupyterlab/jupyterlab-google-drive#44]
I had this installed and then I tried to install the fasta extension, and it killed my google-drive extension. Not exactly sure where to start, but since the error seems google-drive specific I figured I'd post it here.

Any ideas?

```
> npm pack /home/dan/git/jupyterlab-google-drive
> node node-version-check.js
> npm pack /home/dan/git/jupyterlab-google-drive
> npm install
> npm run build

> @jupyterlab/application-top@0.9.0 build /home/dan/miniconda3/share/jupyter/lab/staging
> webpack

Hash: e9bcfe5bfb724bb83eae
Version: webpack 2.7.0
Time: 6104ms
                                 Asset       Size  Chunks                    Chunk Names
af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]         
  d56f3e79da8724878d9c41502956bcd1.png    42.9 kB          [emitted]         
  3275372707f7d039afebb96123631395.png    5.44 kB          [emitted]         
  7a564d5604efdab6ca2325dcced48457.png  210 bytes          [emitted]         
  995a1d96b1fef026c61ac03f4c6ff841.png  210 bytes          [emitted]         
  200b3fc810ff360a023c4cc309f77e5a.png  217 bytes          [emitted]         
  1c8b268ec020a3aa5cd211cdda05fe2b.png  214 bytes          [emitted]         
  674f50d287a8c48dc19ba404d20fe713.eot     166 kB          [emitted]         
  b1efea7ab3eceaa05d36173c0bcd54fe.png    3.04 kB          [emitted]         
 fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]         
  b06871f281fee6b241d60582ae9369b9.ttf     166 kB          [emitted]         
  fcad2f97acb3c868bd1ca7629d36d80e.svg    16.9 kB          [emitted]         
  912ec66d7572ff821749319396470bde.svg     444 kB          [emitted]  [big]  
                           0.bundle.js     892 kB       0  [emitted]  [big]  
                        main.bundle.js    7.32 MB       1  [emitted]  [big]  main
                       0.bundle.js.map    1.08 MB       0  [emitted]         
                    main.bundle.js.map    8.75 MB       1  [emitted]         main
  [23] ./~/@jupyterlab/application/lib/index.js 4.56 kB {1} [built]
 [461] ./~/@jupyterlab/application-extension/lib/index.js 4.93 kB {1} [optional] [built]
 [462] ./~/@jupyterlab/apputils-extension/lib/index.js 4.55 kB {1} [optional] [built]
 [463] ./~/@jupyterlab/codemirror-extension/lib/index.js 9.34 kB {1} [optional] [built]
 [464] ./~/@jupyterlab/completer-extension/lib/index.js 7.09 kB {1} [optional] [built]
 [465] ./~/@jupyterlab/console-extension/lib/index.js 12.6 kB {1} [optional] [built]
 [466] ./~/@jupyterlab/csvviewer-extension/lib/index.js 1.79 kB {1} [optional] [built]
 [467] ./~/@jupyterlab/docmanager-extension/lib/index.js 7.64 kB {1} [optional] [built]
 [468] ./~/@jupyterlab/faq-extension/lib/index.js 2.04 kB {1} [optional] [built]
 [469] ./~/@jupyterlab/filebrowser-extension/lib/index.js 11.7 kB {1} [optional] [built]
 [470] ./~/@jupyterlab/fileeditor-extension/lib/index.js 11.8 kB {1} [optional] [built]
 [471] ./~/@jupyterlab/google-drive/lib/index.js 10.4 kB {1} [optional] [built]
 [472] ./~/@jupyterlab/help-extension/lib/index.js 8.84 kB {1} [optional] [built]
 [473] ./~/@jupyterlab/imageviewer-extension/lib/index.js 4.25 kB {1} [optional] [built]
 [503] ./build/index.out.js 7.68 kB {1} [built]
    + 1198 hidden modules

ERROR in ./~/@jupyterlab/google-drive/lib/gapi.js
Module not found: Error: Can't resolve 'jquery' in '/home/dan/miniconda3/share/jupyter/lab/staging/node_modules/@jupyterlab/google-drive/lib'
 @ ./~/@jupyterlab/google-drive/lib/gapi.js 6:8-25
 @ ./~/@jupyterlab/google-drive/lib/index.js
 @ ./build/index.out.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @jupyterlab/application-top@0.9.0 build: `webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @jupyterlab/application-top@0.9.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Uninstalling @jupyterlab/google-drive from /home/dan/miniconda3/share/jupyter/lab/extensions
Traceback (most recent call last):
  File "/home/dan/miniconda3/bin/jupyter-labextension", line 6, in <module>
    sys.exit(jupyterlab.labextensions.main())
  File "/home/dan/miniconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/dan/miniconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/dan/miniconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 167, in start
    super(LabExtensionApp, self).start()
  File "/home/dan/miniconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/home/dan/miniconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 89, in start
    raise e
  File "/home/dan/miniconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 85, in start
    build(self.app_dir, logger=self.log)
  File "/home/dan/miniconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 514, in build
    run([npm, 'run', 'build'], cwd=staging, logger=logger)
  File "/home/dan/miniconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 71, in run
    raise error
  File "/home/dan/miniconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 67, in run
    return check_output(cmd, **kwargs)
  File "/home/dan/miniconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/dan/miniconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['npm', 'run', 'build']' returned non-zero exit status 2.
```

**Comment by blink1073** [comment]
Hi @danpf, does it work if you run `jupyter lab clean && jupyter lab build`?

**Comment by danpf** [comment]
That command succeeds, but then re-doing 
`jupyter labextension link .` 
in the google-drive directory installs it (seemingly correctly)
but when I run 
`jupyter lab`
i get 
```
[I 10:24:42.315 LabApp] JupyterLab alpha preview extension loaded from /home/dan/miniconda3/lib/python3.6/site-packages/jupyterlab
JupyterLab v0.26.3
Known labextensions:
   app dir: /home/dan/miniconda3/share/jupyter/lab
        @jupyterlab/google-drive@0.5.0 [32m enabled [0m [32mOK[0m
   linked extensions:
        @jupyterlab/google-drive: /home/dan/git/jupyterlab-google-drive
[E 10:24:42.337 LabApp] shemas_dir: /home/dan/miniconda3/share/jupyter/lab/schemas
[I 10:24:42.339 LabApp] Serving notebooks from local directory: /home/dan/git/jupyterlab-google-drive
[I 10:24:42.339 LabApp] 0 active kernels 
[I 10:24:42.339 LabApp] The Jupyter Notebook is running at: http://localhost:8888/?token=e9835e7e85439420e97fb342e934ac2e725412355624cc8f
[I 10:24:42.339 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:24:42.340 LabApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=e9835e7e85439420e97fb342e934ac2e725412355624cc8f
[I 10:24:42.820 LabApp] Accepting one-time-token-authenticated connection from 127.0.0.1
```
and there is no google drive tab like there used to be.

**Comment by ian-r-rose** [comment]
Are there any errors in the developer console in your web browser?

**Comment by danpf** [comment]
looks like it!
```
Error: Cannot find module "@jupyterlab/google-drive"
    at webpackMissingModule (index.out.js:225)
    at main (index.out.js:225)
main	@	index.out.js:228
```

**Comment by ian-r-rose** [comment]
It looks like you might have more than one verision of `@jupyterlab/google-drive` installed (see the ones listed under `app dir` and `linked extensions`). That may be the source of the problem.

**Comment by danpf** [comment]
I think that's because I installed it from the github repo instead of using 
`jupyter labextension install @jupyterlab/google-drive`
if i uninstall and unlink the previous installation and then run the above command
I get
```
[I 11:28:06.903 LabApp] JupyterLab alpha preview extension loaded from /home/dan/miniconda3/lib/python3.6/site-packages/jupyterlab
JupyterLab v0.26.3
Known labextensions:
   app dir: /home/dan/miniconda3/share/jupyter/lab
        @jupyterlab/google-drive@0.5.0 [32m enabled [0m [32mOK[0m
[E 11:28:06.928 LabApp] shemas_dir: /home/dan/miniconda3/share/jupyter/lab/schemas
[I 11:28:06.930 LabApp] Serving notebooks from local directory: /home/dan/git/jupyterlab-google-drive
[I 11:28:06.931 LabApp] 0 active kernels 
[I 11:28:06.931 LabApp] The Jupyter Notebook is running at: http://localhost:8888/?token=f17128bfff7ebc9ee578ba0a8637400145a06adc8f94d63e
[I 11:28:06.931 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:28:06.931 LabApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=f17128bfff7ebc9ee578ba0a8637400145a06adc8f94d63e
[I 11:28:07.447 LabApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[I 11:28:09.585 LabApp] interrupted
Serving notebooks from local directory: /home/dan/git/jupyterlab-google-drive
0 active kernels 
The Jupyter Notebook is running at: http://localhost:8888/?token=f17128bfff7ebc9ee578ba0a8637400145a06adc8f94d63e
```
same thing though, no google drive tab

**Comment by danpf** [comment]
Okay so if i then run
`jupyter lab clean && jupyter lab build`
THEN i can see the drive tab when I run `jupyter lab`

So this is probably some weird overlap bug when I install using the
`jupyter labextension link .` command with multiple labextensions? I can do some more messing around for you, or i can close the issue and mark as resolved :D

**Comment by ian-r-rose** [comment]
Glad to hear it! I am happy to mark it as resolved, but feel free to reopen if you come across other strange install interactions.
